### ISSUE TITLE
GVM Tool to use mostly Groovy instead of Bash?

### ISSUE THREAD

**Issue by hansgru** [gvmtool/gvm-cli#344]
Hi,

gvm-cli seems to do most of the stuff in Bash :(.
Is there any chance that most of it to be converted to Groovy code ?

Because of the intense Bash use, GVM is not working on Windows :(.

I know, there's Posh-gvm (for windows) but because of the PowerShell requirement, it doesn't seems to be usable in most business environments  :(.

Thank you.

**Comment by flofreud** [comment]
> I know, there's Posh-gvm (for windows) but because of the PowerShell requirement, it doesn't seems to be usable in most business environments :(.

Could you describe this issue, please? I would like to understand what stops you from using PowerShell while using Windows.

**Comment by hansgru** [comment]
> Can you describe this issue, please? I would like to understand what stops you from using PowerShell while using Windows.

It's not working from the user's perspective in most "corporate environments". Usual causes I've encountered:
- it's rights problem: users don't have the rights to run it (it's supposed to be used only by admins)
- it's a version problem. Poweshell 3+ is practically non-existing in most companies: Windows 8 too :).
- proxy restrictions for powershell

Mostly is a combination of all above why powershell scripts won't work.

Note that GIT, Java, Groovy, Maven and Gradle, are working in all the above environments without problems, hence my request for a Groovy (or Java) based GVM solution.

**Comment by flofreud** [comment]
What would be your use case for GVM? Using GVM for downloading of the binaries only? Maybe https://github.com/gvmtool/gvm-sdk could help you with some additional lines of code.

Or should GVM also handles the env config of your shell? This could not be handled directly by a Groovy port. 

It would be possible to do certain cases in Windows environment like setting the new default version to use, but you would have to restart / force to reload the environment for all programs using this settings.

If your use case contains also the environment management: what is this environment like? If Powershell is prohibited by the group policies, which shell do you use?

**Comment by hansgru** [comment]
> What would be your use case for GVM? Using GVM for downloading of the binaries only?

Handling several Grails/Groovy/Gradle versions on the same machine, since not all projects can be migrated to use always only one Grails version.

> Or should GVM also handles the env config of your shell? This could not be handled directly by a Groovy port. 

Why not? 
I "solved" in a primitive way this problem on windows by having ```GROOVY_HOME``` and ```GRAILS_HOME``` pointing to a ```c:/installed/groovy``` and ```c:/installed/grails``` directory that never changes, but are Windows Directory Links to each desired version.

I'm changing these links with a simple Groovy Script depending on what project I need to work on.

> If Powershell is prohibited by the group policies, which shell do you use? 

On windows there's only the standard "cmd', so BAT files work.

**Comment by flofreud** [comment]
> Why not? I "solved" in a primitive way this problem on windows by having GROOVY_HOME and GRAILS_HOME pointing to a c:/installed/groovy and c:/installed/grails directory that never changes, but are Windows Directory Links to each desired version.

GVM also allows to change the used version for the current shell only like `gvm use groovy 2.0.0`. 
The junction-based solution is only helpful for the global use case (and is used by posh-gvm and also via symlinks in gvm-cli).

For the usage with CMD a plain BAT implementation or a Groovy-based implementation (which would probably have a reduced feature set), would certainly be helpful, but they are no direct replacements for the available implementations. A Groovy-based implementation would also cause a chicken-and-egg problem.

Providing new clients for the GVM API is encouraged and it sounds like you have already everything in place for your use case. With https://github.com/gvmtool/gvm-sdk (which can manage the .gvm-dir + install new versions) in combination with the code for the junction-creation in your script and some code for the processing of the commands (eg with help of http://docs.groovy-lang.org/latest/html/gapi/groovy/util/CliBuilder.html), you could provide a Groovy-based client for all of us to use. :)

As I wrote posh-gvm I evaluated a similar solution but dropped it for supporting the whole set of GVM features. I also didn't wrote a CMD-BAT client because of the additional dependencies for downloading, extraction etc. needed. For me Powershell is a better shell as CMD so I wrote a Powershell client. 

Another alternative could be a CYGWIN-distribution (eg Babun) but those would probably not working either in restricted corporate environments.

**Comment by hansgru** [comment]
> For the usage with CMD a plain BAT implementation or a Groovy-based implementation (which would probably have a reduced feature set), would certainly be helpful, but they are no direct replacements for the available implementations. 

My hope was that a Groovy implementation would cover most of the logic that is mostly not OS dependent but done twice (with bash and powershell too), and only have in ```bash``` and ```bat``` a very small part so that itt would not require two separate projects.

> A Groovy-based implementation would also cause a chicken-and-egg problem.

I don't see why. A private version of Groovy only for the tool (only a simple jar used by the tool only).

> I also didn't wrote a CMD-BAT client because of the additional dependencies for downloading, 

If most stuff it's done in Groovy and only a small part remains as BAT, I don't think there's any download needed besides the tool itself.

**Comment by marcoVermeulen** [comment]
@hansgru The reason why bash was chosen is because it's the lowest common denominator across all platforms. Simply put, bash is almost everywhere, including on windows in the form of cygwin, which btw works perfectly. On top of that, you have @flofreud's incredible work to choose from in the form of POSH GVM, something that he took on all by himself as an alternative to the bash client.

I'm a firm believer in that you always use the right tool for every job. When writing a CLI client, I use what's best for CLI clients. __Bash__.

Groovy is _not_ fit for purpose in a situation like this, as you necessitate the presence of a JDK. Also, you always wrestle with slow start up times. Even though we all fancy one particular language doesn't mean that _everything_ needs to be written in that one language.

For these reasons, this tool will always be CLI first, whether it be bash or power shell. For IDE and site developers, we provide the SDK, which gives you access to the API through a Java library.

**Comment by hansgru** [comment]
> When writing a CLI client, I use what's best for CLI clients. Bash.

According to this logic, the grails interactive shell should be written in Bash too :).
I'm glad it's not, since it can do so many stuff. I get that it must be a Bash/BAT entry point, but the rest of the stuff IMHO it's arbitrary.

> Groovy is not fit for purpose in a situation like this, as you necessitate the presence of a JDK. 

As do **every** library GVM (**Groovy** enVironment Manager) is managing depending on Java :), so it's always a prerequisite.

**Comment by marcoVermeulen** [comment]
What logic is it that you speak of? Grails is a Groovy and Java product, hence the REPL is obviously written in Java and Groovy. GVM is _not_ a Java or Groovy product.

Just because you like one language doesn't mean that you have to use it for _everything_. Good craftsmen learn to use, respect and appreciate _all_ languages. This is true polyglot programming.

__GVM__, the __Groovy__ enVironment Manager is about to be renamed to __SDKman__. Guess what, it won't just be hosting _Groovy_ SDKs, or even _Java_ SDKs. It will host any kind of Software Development Kit under the sun. _THAT_ is why it will not be dependent on Java or Groovy.

Just to be clear, I _love_ Groovy and use it daily. I'm just open minded enough to use other languages too where they have merit. Bash is a great language in it's own right.
